### ISSUE TITLE
Implement Add/Edit functionality for all contacts

### ISSUE THREAD

**Issue by mayank99** [multacc/multacc#104]
See `connector` implementation from #125

**Comment by TortoiseWrath** [comment]
The best way to do this is to add an "edit contact" page. **This is the same page as the profile editing page #25**

**Comment by TortoiseWrath** [comment]
> ```abstract class Connector {
  connect();
}

class TwitterConnector extends Connector {
  TwitterItem connect() {
    // Connect to Twitter
 // Return a TwitterItem
  }
}

extension MultaccItemTypeInfo on MultaccItemType {
  dynamic get icon {}
  dynamic get name {}
  bool isConnectable() {}
  bool isInputtable() {} // false for GroupMe, etc
  MultaccItem createItem() {} // create an empty item with this type
  Connector connector() {
    switch (t) {
   case TwitterItemType:
     return TwitterConnector();
   // etc
   default:
     return null;
 }
  }
}

// in the frontend: something along the lines of
for (final t in MultaccItemType.values) {
  // add type to the list of available types with action create(t)
}

void create(MultaccItemType t) {
  if (t.isConnectable() &amp;&amp; t.isInputtable()) {
    // display choice
  } else if (t.isConnectable()) {
    Connector connector = Connector(t);
 profile.items += connector.connect();
  } else if (t.isInputtable()) {
    profile.items += t.createItem();
    // create a text box that calls setValue() on th
  } else {
    // automatically open an issue in multacc repo
  }
}```
<sub>[View in Slack](https://cs495-group-workspace.slack.com/archives/CSD5JKT0F/p1584049969005400)</sub>

**Comment by TortoiseWrath** [comment]
^ that, but without the abstract class

Raising to P1 due to this blocking #25 and that the above modifies the existing MultaccItem model.

A big part of the logic here is implementing the above extension to MultaccItemType, which also modifies the existing MultaccItem model due to the relocation of icon and name.

@mayank99 Who is implementing those logic changes? I can do it today or tomorrow but idk if you are already working on it or planning to.

**Comment by mayank99** [comment]
I was working on #16 so you can do this one. There's really no rush anymore lol
