### ISSUE TITLE
Store personal profile in local db

### ISSUE THREAD

**Issue by mayank99** [multacc/multacc#68]
- Maybe in a different box or in the same contacts box for now
- Will help with all the logic for displaying and sharing profile
- Different box would help store "saved templates" too
- Related to #25

**Comment by TortoiseWrath** [comment]
bruh I was halfway through writing this issue

**Comment by TortoiseWrath** [comment]
We should have a separate box for data with known keys that are under multacc's control (such as the profile page, user settings, whatever else ends up in the box). We really have no control over the keys in contacts box since they come from outside multacc.

Users should be able to choose separately whether to back up their "Contacts" and "Multacc settings" to the multacc server someday.

**Comment by TortoiseWrath** [comment]
Is this blocked on #68 or is #68 blocked on this?

**Comment by mayank99** [comment]
I don't think either of them are blocked. #25 mainly refers to the UI, #68 mainly refers to the logic/db. I guess if you considered #25 to be the whole feature (rather than just the UI), then it's blocked on #68.
